# Generated by Django 3.0.6 on 2020-05-27 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summerschool', '0003_schoollogincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='age',
        ),
        migrations.RemoveField(
            model_name='school',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name_of_parent_or_guardian',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school',
        ),
        migrations.CreateModel(
            name='SchoolKid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('school', models.CharField(choices=[('GradeSchool', 'GradeSchool'), ('PreSchool', 'PreSchool'), ('Kindergarten', 'Kindergarten')], max_length=20)),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10)),
                ('photo', models.ImageField(blank=True, default='kphotos.jpg', upload_to='kids_photos')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
