# Generated by Django 3.0.6 on 2020-05-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerschool', '0004_auto_20200527_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolkid',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], help_text="Use this field only if child's school is GradeSchool", max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolkid',
            name='photo',
            field=models.ImageField(blank=True, default='parents-icon-png-29.jpg', upload_to='kids_photos'),
        ),
    ]
