# Generated by Django 3.0.6 on 2020-05-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerschool', '0005_auto_20200527_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolkid',
            name='photo',
            field=models.ImageField(blank=True, default='kid.jpg', upload_to='kids_photos'),
        ),
    ]
