# Generated by Django 3.0.6 on 2020-06-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summerschool', '0006_auto_20200527_0733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolLoginCode',
        ),
    ]
