# Generated by Django 3.0.6 on 2020-08-01 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summerschool', '0007_delete_schoollogincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usefulness', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, help_text='On a scale of 1 to 10 how useful was the summerschool?')),
                ('participate', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', help_text='Would you participate again if organized next time?', max_length=4)),
                ('recommend', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', help_text='Would you recommend a friend next time?', max_length=4)),
                ('something_new', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', help_text='Did your ward learn something new?', max_length=4)),
                ('date_answered', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
