# Generated by Django 3.0.6 on 2020-08-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerschool', '0010_auto_20200802_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='something_new',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', help_text='Did your ward learn anything new?', max_length=4),
        ),
    ]
