# Generated by Django 3.0.6 on 2020-08-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerschool', '0011_auto_20200802_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='improvement',
            field=models.TextField(blank=True, default='', help_text='Is there something that needs improvement in our summer school?.Give us suggestions'),
        ),
    ]
