# Generated by Django 3.0.6 on 2020-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerschool', '0012_auto_20200802_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='ratings',
            field=models.IntegerField(default=5, help_text='How would you rate our summer school?'),
        ),
    ]
