# Generated by Django 3.0.6 on 2020-08-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerschool', '0013_auto_20200802_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='improvement',
            field=models.TextField(blank=True, default='', help_text='Is there something that needs improvement in our summer school?.Give us suggestions', max_length=200),
        ),
    ]
