# Generated by Django 3.0.6 on 2020-07-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaged',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='online_user',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageD',
        ),
        migrations.DeleteModel(
            name='Online_user',
        ),
    ]
