# Generated by Django 3.0.6 on 2020-07-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_usersurvey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usersurvey',
            name='on_a_scale_of_one_ten_how_useful_was_the_summer_school',
        ),
        migrations.AddField(
            model_name='usersurvey',
            name='usefulness',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default='10', help_text='On a scale of 1 to 10 how useful was the summerschool?', max_length=4),
        ),
    ]
