# Generated by Django 3.0.6 on 2020-07-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200731_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='usefulness',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, help_text='On a scale of 1 to 10 how useful was the summerschool?'),
        ),
    ]
