# Generated by Django 3.0.6 on 2020-07-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_report_report_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_doc',
            field=models.FileField(blank=True, help_text='Your file should be .pdf,.docs,txt', upload_to='report_documents'),
        ),
    ]
