# Generated by Django 3.0.6 on 2020-08-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200801_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSurvey',
        ),
    ]
