# Generated by Django 3.0.6 on 2020-08-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_usersurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_created=True)),
                ('review_content', models.CharField(max_length=400)),
                ('reviewer', models.ImageField(blank=True, default='reviewer.jpg', upload_to='reviews_pics')),
                ('ratings', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, max_length=3)),
            ],
        ),
    ]
