# Generated by Django 3.0.6 on 2020-08-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ratings',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
