# Generated by Django 3.0.6 on 2020-08-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200801_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
