# Generated by Django 3.0.6 on 2020-08-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200801_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_content',
            field=models.TextField(max_length=400),
        ),
    ]
